[font]
size = 8


[[font.normal]]
family = "ComicCodeLigatures NF"
style = "Regular"

# You can set a different font for fallback
[[font.normal]]
family = "JetBrainsMono Nerd Font"
style = "Regular"

