#!/usr/bin/env bash

set -euo pipefail

echo "🚀 Welcome to the jvegaf/dotfiles installer!"
echo "-------------------------------------------------"
echo

if grep -qEi "(archlinux)" /proc/version &>/dev/null; then
  echo "Installing previuos dependencies"
  sudo pacman -S git base-devel rustup --noconfirm --needed
  rustup default stable
elif grep -qEi "(cachyos)" /proc/version &>/dev/null; then
  echo "Installing previuos dependencies"
  sudo pacman -S git base-devel rustup --noconfirm --needed
  rustup default stable
elif grep -qEi "(manjaro)" /proc/version &>/dev/null; then
  echo "Installing previuos dependencies"
  sudo pacman -S git base-devel rustup --noconfirm --needed
  rustup default stable
else
  echo "Installing previuos dependencies"
  sudo apt-get update && sudo apt-get install -y build-essential fzf fonts-powerline python3-pip python-is-python3 python3-venv
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi

export PATH="$HOME/.cargo/bin:$PATH"
cargo install docpars lsd git-delta bat grip-grab

export DOTFILES_PATH="$HOME/.dotfiles"
echo "👉  Cloning into: '$DOTFILES_PATH'"

git clone --recurse-submodules -j8 --depth 1 https://github.com/jvegaf/dotfiles.git "$DOTFILES_PATH"
export DOTLY_PATH="$DOTFILES_PATH/modules/dotly"

echo "Installing dotly 🌚"
"$DOTLY_PATH/bin/dot" self install

echo "Symlinks apply"
"$DOTLY_PATH/bin/dot" symlinks apply

echo "Installing Linux Packages"
"$DOTLY_PATH/bin/dot" self install_custom
