#!/usr/bin/env bash

git clone -q --depth=1 https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh
git clone -q --depth=1 https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
git clone -q --depth=1 https://github.com/zsh-users/zsh-autosuggestions.git ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions



# Pacman eye-candy features
echo "→ Enabling colours and parallel downloads for pacman..."
sudo sed -Ei 's/^#(Color)$/\1/;s/^#(ParallelDownloads).*/\1 = 10/' /etc/pacman.conf
#
# # Setup rust
# echo "→ Installing Rust..."
# sudo pacman -S --needed --noconfirm rustup
# rustup default stable
#
# # Install paru AUR Helper
# check_paru="$(sudo pacman -Qs paru | grep "local" | grep "paru")"
# if [ -n "${check_paru}" ]; then
#   echo "→ Installing paru..."
#   sudo pacman -S --needed --noconfirm base-devel
#   git clone https://aur.archlinux.org/paru.git /tmp/paru
#   cd /tmp/paru
#   makepkg -si --needed --noconfirm
# fi
