# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(161219)
$foreground = rgb(F1D7EF)
$color0 = rgb(3D3A41)
$color1 = rgb(4600BF)
$color2 = rgb(4602BF)
$color3 = rgb(59475C)
$color4 = rgb(705577)
$color5 = rgb(A95C6D)
$color6 = rgb(A0699E)
$color7 = rgb(E2BDE0)
$color8 = rgb(9E849D)
$color9 = rgb(5D01FE)
$color10 = rgb(5E02FF)
$color11 = rgb(765F7B)
$color12 = rgb(96719F)
$color13 = rgb(E17A91)
$color14 = rgb(D68CD2)
$color15 = rgb(E2BDE0)
