#!/usr/bin/env bash
set -eo pipefail

# usage menu
function show_usage() { #{{{
  echo -e "USAGE:\t$0 powersave|performance|current"
  echo -e "\t\tpowersave\tSet CPU in power-saving mode."
  echo -e "\t\tperformance\tSet CPU in performance mode."
  echo -e "\t\tcurrent\t\tShow the current CPU mode."
  echo -e "\t\thelp\t\tShow this menu."
  exit 1
} #}}}

# our error exit function
function ee() { #{{{
  echo "$1"
  exit 1
} #}}}

# get cpu mode
function getcpumode() { #{{{
  cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
} #}}}

# set cpu mode
function setcpumode() { #{{{
  [ "$1" != 'powersave' -a "$1" != 'performance' -a "$1" != 'schedutil' ] && ee 'Invalid given value..'
  [ $(getcpumode) == "$1" ] && ee "It's already in '$1' mode"
  echo "$1" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
} #}}}

# get & set actions
case "$1" in #{{{
performance)
  setcpumode performance
  exit 0
  ;;
schedutil)
  setcpumode schedutil
  exit 0
  ;;
powersave)
  setcpumode powersave
  exit 0
  ;;
current | get)
  getcpumode
  exit 0
  ;;
help) show_usage ;;
*) ee "Try: $0 help" ;;
esac #}}}
