# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules
# This file will not be modified during dotfiles updates


windowrule = tag +music, match:class ^([Ss]ymphony)$
windowrule = tag +music, match:class ^([Hh]armony)$
windowrule = match:title ^(Developer Tools - http://localhost:5173/)$, tag +multimedia
windowrule = match:class ^(com.rtosta.zapzap)$, tag +im

windowrule = workspace 4, match:tag music*
windowrule = workspace 7, match:tag im*
windowrule = workspace 9 silent, match:tag multimedia*
windowrule = match:class ^(FreeCAD)$, tag +music


