# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #C3D8E0
background         #131414
cursor             #7B959F

active_tab_foreground     #131414
active_tab_background     #C3D8E0
inactive_tab_foreground   #C3D8E0
inactive_tab_background   #131414

active_border_color   #C3D8E0
inactive_border_color #131414
bell_border_color     #1E2E35

color0      #3B3B3C
color1		#1E2E35
color2		#263E47
color3		#2F4D59
color4		#375D6B
color5		#3F6C7D
color6		#3F6C7D
color7		#A1BFCB
color8		#71868E
color9		#283D46
color10		#33525F
color11		#3E6777
color12		#497B8F
color13		#5490A7
color14		#5490A7
color15		#A1BFCB
