# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #B6CFBC
background         #101113
cursor             #60726C

active_tab_foreground     #101113
active_tab_background     #B6CFBC
inactive_tab_foreground   #B6CFBC
inactive_tab_background   #101113

active_border_color   #B6CFBC
inactive_border_color #101113
bell_border_color     #060D14

color0      #38393B
color1		#060D14
color2		#071015
color3		#162B20
color4		#182F22
color5		#182F22
color6		#225931
color7		#8EB398
color8		#637D6A
color9		#08121B
color10		#0A151C
color11		#1D392B
color12		#203F2D
color13		#203F2D
color14		#2E7741
color15		#8EB398
